### PR TITLE
Ben's changes for markdown support

### PR DESCRIPTION
**Pull request by PaulJackson123**
Ben says there should already be a PR in stardog that goes with this.

### CODE REVIEW

**Comment by PaulJackson123** [comment]
Looks like there may need to be some version stuff done?

Also, this is the git log from his work folder, so looks like his branch was off `master`.
```
airline $ git log
commit 0e4956e21b3e9b7d1b57fcdb5095530fb2aa9a64 (HEAD -> fix/markdown, tag: 0.7.8, origin/master, origin/HEAD, master)
Author: Toktarev Alexander <toktarev@stardog.com>
Date:   Tue Feb 18 13:02:29 2020 +0300

    Bump gradle and guava version

```

**Comment by noahgorstein** [comment]
> Ben says there should already be a PR in stardog that goes with this.

I think its https://github.com/stardog-union/stardog/pull/9387/files . We should bump the version I suppose. So does this jar from airline get pushed into artifactory somehow? Or does it needs to be installed locally?

**Comment by PaulJackson123** [comment]
> > Ben says there should already be a PR in stardog that goes with this.
> 
> I think its https://github.com/stardog-union/stardog/pull/9387/files . We should bump the version I suppose. So does this jar from airline get pushed into artifactory somehow? Or does it needs to be installed locally?

Ben said he discussed with @snowell about loading the jar into artifactory. Would make sense to replace it with the official build from this source, I think.

**Comment by snowell** [comment]
@PaulJackson123 @noahgorstein Yes, before he left Ben compiled this jar and we placed it in the cp-internal repository where our build(s) have been pulling this dependency as long as I can remember. The stardog PR Noah linked to is that update.

**Comment by PaulJackson123** [comment]
Should we bump this version to "0.7.9" or something higher ("0.8.0", "0.7.10", ...)?

**Comment by noahgorstein** [comment]
Unclear to me - it looks like the source project it is originally forked from is [no longer maintained](https://github.com/airlift/airline/pull/74/files) as of ~2 months ago. Last released version was 0.8.0 from what I can tell.

I've pulled Ben's branch down locally and have had to make some changes to the code in order for the man pages to play nicely with the jekyll, the static site generator we're using to generate the docs. For now, we can close this PR and I'll open up a new one when I have things finalized.

**Pull request closed without merging**
